apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: "NUIzdFBRb1F2cmZPUEFCb3lpeXpsRDhmWWpZVThNdTRCbGlBZ3hId2ViSHM0TlFHa3ZRd0pRUUo5OUJEQUNmaE1rNVhKM3czQUFBQUFDT0dYNmdi"

---
apiVersion: v1
kind: Secret
metadata:
  name: azure-servicebus-secret
type: Opaque
stringData:
  AZURE_SERVICE_BUS_CONNECTION_STRING: "Endpoint=sb://bbservicebus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=eIJwPY2UllIz0ZKRBm9jQGaL0+sWGKRcQ+ASbIu/TPs="
  ORDER_QUEUE_NAME: "orders"

---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
stringData:
  ORDER_QUEUE_USERNAME: "sender"
  ORDER_QUEUE_PASSWORD: "4Y6CZfkPStlXYs7H7UpnmIPkh3tfRRAtW+ASbEmGYcw="
  ORDER_QUEUE_URI: "amqps://bbservicebus.servicebus.windows.net"
  ORDER_QUEUE_NAME: "orders"
---
apiVersion: v1
kind: Secret
metadata:
  name: makeline-service-secret
type: Opaque
stringData:
  ORDER_QUEUE_USERNAME: "listener"
  ORDER_QUEUE_URI: "amqps://bbservicebus.servicebus.windows.net"
  ORDER_QUEUE_PASSWORD: "UoWv94zNj2fSFn25xSp972BsjzQWuINUy+ASbLKdrAo="
  ORDER_QUEUE_NAME: "orders"
